export const CONFIG = {
  player: {
    initialSize: 1,
    initialSpeed: 260,
    minSpeed: 210,
    speedLossPerSize: 25,
    startXRatio: 0.28,
    startYRatio: 0.5,
    targetLengthRatio: 1.05,
    minTargetSize: 4.2,
  },
  spawning: {
    maxFish: 10,
    interval: 0.9,
    dangerDelay: 10,
    dangerEarlyProgress: 0.28,
    dangerStopProgress: 0.55,
    dangerChanceEarly: 0.38,
    dangerChanceMid: 0.2,
    maxDangerFishEarly: 2,
    maxDangerFishMid: 1,
    dangerAvoidPlayerY: 120,
    dangerPassageByPlayerHeight: 1.25,
    dangerSpawnAttempts: 18,
    sidePadding: 90,
  },
  fishSize: {
    smallMin: 0.45,
    smallMax: 0.8,
    dangerMin: 1.25,
    dangerMax: 1.55,
  },
  growth: {
    earlyMultiplier: 0.07,
    lateMultiplier: 0.18,
    earlyMinPerFish: 0.025,
    lateMinPerFish: 0.09,
    earlyMaxPerFish: 0.06,
    lateMaxPerFish: 0.62,
  },
  collision: {
    radiusXByLength: 0.3,
    radiusYByHeight: 0.36,
  },
  smallFishBehavior: {
    fleeBaseRange: 120,
    fleeRangeByPlayerSize: 18,
    fleeBaseSpeed: 76,
    fleeSpeedBySizeGap: 104,
    fleeMaxBonusSpeed: 420,
    fleeSteering: 0.12,
    returnSteering: 0.05,
  },
  timing: {
    victoryMinSeconds: 60,
    victoryMaxSeconds: 120,
  },
  world: {
    minWidth: 320,
    minHeight: 240,
    fishBaseLength: 44,
    fishBaseHeight: 22,
  },
};
